### ISSUE TITLE
Unicode is there!  Meet `⁇`.

### ISSUE THREAD

**Issue by akimd** [kibiz0r/coalesce#1]
Hi,

This is not an issue, just a comment.

I like `_?` very much: it's very unlikely to be used elsewhere, and easy to type.  But, FTR, I have used the same idea, but getting wilder on Unicode.  Of course, it's somewhat less convenient to type, but nice looking.

Cheers.

```ruby
class Object
  def ⁇(x = nil)
    self
  end
end

class NilClass
  def ⁇(x = nil)
    if block_given?
      yield
    else
      x
    end
  end
end

nil.⁇ { puts 1; 1}.⁇{ puts 2; 2}
```

```
$ ruby /tmp/coal.rb
1
```

**Comment by kibiz0r** [comment]
That's pretty cool!

But I'd worry about coworkers trying to write `??` and wondering why it doesn't work.

If you use font ligatures, `??` may end up rendering the same thing as `⁇`. I use FiraCode, whose entry for `??` looks almost-but-not-quite identical to `⁇`.

Without ligatures:

![image](https://github.com/kibiz0r/coalesce/assets/118859/eef795bc-39d1-4e77-aba1-16f5794be72b)

With ligatures:

![image](https://github.com/kibiz0r/coalesce/assets/118859/fc7f4605-c323-4f05-b99c-194d3578329f)

That said, if it works for you, go for it!
